import { RoadmapArea, Module } from '../types';

export const TECH_BUSINESS_ROADMAP_AREAS: RoadmapArea[] = [
  {
    id: 'tb-501',
    name: 'Technical Product Management & SaaS Economics',
    description: 'Aligning software architectures with corporate monetization models, unit economics, and product market fit.',
    icon: 'Cpu',
    color: 'blue',
    courseGroup: 'tech_business'
  },
  {
    id: 'tb-502',
    name: 'Quantitative Risk Management & Security Economics',
    description: 'Translating technical vulnerabilities, threat matrices, and network uptimes into financial metrics and SLAs.',
    icon: 'Shield',
    color: 'rose',
    courseGroup: 'tech_business'
  },
  {
    id: 'tb-503',
    name: 'Data-Driven Growth Marketing & Modern AdTech',
    description: 'Designing user tracking networks, data architectures, and attribution lines that power digital growth.',
    icon: 'Activity',
    color: 'violet',
    courseGroup: 'tech_business'
  },
  {
    id: 'tb-504',
    name: 'Developer-Led Growth (B2B Marketing for Dev Tools)',
    description: 'Selling developer platforms, APIs, and cloud software directly to engineering teams through DX and DevRel.',
    icon: 'Terminal',
    color: 'emerald',
    courseGroup: 'tech_business'
  }
];

export const TECH_BUSINESS_MODULES: Module[] = [
  {
    id: 'mod-tb-501',
    areaId: 'tb-501',
    title: 'Technical Product Management & SaaS Economics',
    description: 'Master SaaS ledgers (LTV, CAC, Churn) and rapidly test feature market validation through MVPs.',
    libraryLinks: [
      { title: "SaaS Metrics Explained - Slidebean", url: "https://www.youtube.com/watch?v=gTshZ6YV9wM" },
      { title: "Finding Product-Market Fit - Y Combinator", url: "https://www.youtube.com/watch?v=0P7nC6sE684" }
    ],
    lessons: [
      {
        id: 'tb501-l1',
        moduleId: 'mod-tb-501',
        title: 'Unit 1: The Software-as-a-Service (SaaS) Ledger',
        duration: 30,
        youtubeVideoId: 'gTshZ6YV9wM',
        content: `### The Software-as-a-Service (SaaS) Ledger

To build sustainable software, we must translate application scalability directly into financial durability. This unit details the core unit economics of the SaaS business model.

---

#### 1. Core Financial Metrics of SaaS
A SaaS company's valuation and survival are governed by specific client indicators:
* **Customer Acquisition Cost (CAC):** The total financial spend (marketing + sales) required to land one paying customer.
* **Lifetime Value (LTV):** The total revenue estimated to be generated by a user account before they close their profile.
* **Churn Rate:** The percentage of users who cancel their service memberships during a specific period.
* **SaaS Health Ratio (LTV:CAC):** Excellent SaaS enterprises strive for a ratio of **3:1** or higher.

#### 2. Engineering Alignment to Business Lifecycles
* **Performance Impact on Churn:** Latency, system memory crashes, and UI bugs have a direct, measurable impact on customer churn. Shaving 100ms off database query times directly preserves corporate LTV metrics.
* **SaaS Paywall Architectures:**
  * *Usage-Based:* Charging by consumed API limits or storage volume.
  * *Tiered Feature Access:* Gatekeeping premium security keys or advanced dashboard controls.
  * *Per-Seat Models:* Locking team accounts of different volumes to structural enterprise levels.`,
        quiz: {
          id: 'q-tb501-l1',
          title: 'SaaS Economics Check',
          questions: [
            {
              id: 'q-tb501-l1-1',
              text: 'If a company spends $10,000 on ads to acquire 100 users, and each user yields $300 in lifetime income, what is their LTV:CAC ratio?',
              options: ['1:1', '2:1', '3:1', '4:1'],
              correctAnswerIndex: 2,
              explanation: 'The CAC is $10,000 / 100 = $100. Since individual LTV is $300, the ratio is 300:100, which simplifies to 3:1 (optimal SaaS baseline).'
            }
          ]
        }
      },
      {
        id: 'tb501-l2',
        moduleId: 'mod-tb-501',
        title: 'Unit 2: Minimum Viable Product (MVP) & Product-Market Fit',
        duration: 25,
        youtubeVideoId: '0P7nC6sE684',
        content: `### MVP & Product-Market Fit (PMF)

Engineering teams are prone to over-complicating technical concepts before verifying human demand. This unit details how to manage the build-measure-learn cycle.

---

#### 1. Feature Prioritization & Customer Discovery
* **User Story Mapping:** Isolating critical tasks a customer needs to resolve versus non-essential "polishing".
* **Build-Measure-Learn Loop:** Launching early feature modules to capture real-world user activity, feeding those learnings immediately back into source code changes.

#### 2. Engineering Lean Modular Codebases
* **SaaS Speed vs. Absolute Polish:** Deploying initial web screens using clean component libraries (e.g., React and standard hooks) to capture client feedback before building complicated, scalable back-end databases.
* **Reducing Preemptive Scale:** Avoiding complex distributed consensus systems or multi-region failovers when your initial target market is only 50 local beta testers.`,
        quiz: {
          id: 'q-tb501-l2',
          title: 'MVP Delivery Check',
          questions: [
            {
              id: 'q-tb501-l2-1',
              text: 'What is the primary objective when designing and launching a Minimum Viable Product?',
              options: ['To prove that the database can scale to one billion concurrent request hits', 'To capture maximum validated learning about real customers with the least overall development effort', 'To write fully polished, legacy-proof production source directories', 'The display of corporate financial credits on a marketing landing page'],
              correctAnswerIndex: 1,
              explanation: 'An MVP is designed to test business hypotheses with real-world users as fast as possible to avoid over-engineering features nobody wants.'
            }
          ]
        }
      }
    ]
  },
  {
    id: 'mod-tb-502',
    areaId: 'tb-502',
    title: 'Quantitative Risk Management & Security Economics',
    description: 'Calculate financial expectancies of vulnerabilities (ALE, ROSI) and construct robust SLA network structures.',
    libraryLinks: [
      { title: "Cyber Risk Management Fundamentals", url: "https://www.youtube.com/watch?v=OveA_b_i2_w" },
      { title: "Compliance vs Security Explained", url: "https://www.youtube.com/watch?v=jsS9v_7qO6M" }
    ],
    lessons: [
      {
        id: 'tb502-l1',
        moduleId: 'mod-tb-502',
        title: 'Unit 1: Cyber Risk Financialization',
        duration: 35,
        youtubeVideoId: 'OveA_b_i2_w',
        content: `### Quantifying Technical Risk in Financial Metrics

To advocate for proper security spending, a security engineer must translate technical threats and vulnerabilities into standard, balance-sheet calculations. This unit details how to project risk financially.

---

#### 1. The Core Risk Equations
Enterprise boards do not evaluate security using abstract threat ratings. They react to mathematical risk exposures:
* **Single Loss Expectancy (SLE):** The complete financial impact of a single security breach incident.
* **Annual Rate of Occurrence (ARO):** The estimated frequency of a breach incident occurring during a single calendar year.
* **Annual Loss Expectancy (ALE):** The total projected annual loss calculated as:

$$\\text{ALE} = \\text{SLE} \\times \\text{ARO}$$

#### 2. Calculating Return on Security Investment (ROSI)
* **ROI in Cyber Environments:** Justifying a security expense (such as a firewall purchase or penetrative auditing contract) by showing it reduces the ALE.
* **Financial Mitigation Mapping:** If a $50,000 WAF subscription reduces high-risk database breaches from occurring twice a year (ALE of $300,000) to zero, the enterprise preserves $250,000 in net capital.`,
        quiz: {
          id: 'q-tb502-l1',
          title: 'Risk Metric Calculation',
          questions: [
            {
              id: 'q-tb502-l1-1',
              text: 'If a database storage leak costs $200,000 per incident (SLE) and is projected to occur once every two years (ARO = 0.5), what is the Annual Loss Expectancy (ALE)?',
              options: ['$50,000', '$100,000', '$200,000', '$400,000'],
              correctAnswerIndex: 1,
              explanation: 'Using the formula ALE = SLE * ARO, we get $200,000 * 0.5 = $100,000. This represents the yearly financial loss expected if untreated.'
            }
          ]
        }
      },
      {
        id: 'tb502-l2',
        moduleId: 'mod-tb-502',
        title: 'Unit 2: SLAs, Insurance, & Global Compliance Audits',
        duration: 30,
        youtubeVideoId: 'jsS9v_7qO6M',
        content: `### Compliance, Insurance, & Service Level Agreements

Service uptime and data privacy controls are bound by legal and compliance frameworks. We detail their engineering underpinnings in this unit.

---

#### 1. SLA Uptimes & Penalty Metrics
* **Service Level Agreements (SLAs):** Legal promises of network uptime made to business clients.
  * *Five Nines Uptime:* Designing networks that experience less than 5.26 minutes of total downtime *per year* (99.999% uptime).
* **Engineering Action Paths:** Building high-availability load balancers, multi-master replication pools, and dynamic routing to prevent SLA-linked financial penalties.

#### 2. Compliance Framework Audits & Cyber Insurance
* **Audit Standards:** Structuring network structures to comply with SOC2 Type II, HIPAA, and GDPR directories.
* **Insurance Underwriting:** Decreasing corporate liability insurance premiums by proving that the enterprise enforces MFA, active encryption keys, and persistent SIEM log pipelines.`,
        quiz: {
          id: 'q-tb502-l2',
          title: 'SLA & Audit Check',
          questions: [
            {
              id: 'q-tb502-l2-1',
              text: 'What is the maximum yearly downtime allowed under a strict "Four Nines" (99.99%) uptime SLA constraint?',
              options: ['Approximately 52.6 minutes', 'Approximately 5.26 minutes', 'Approximately 8.7 hours', 'Approximately 24 hours'],
              correctAnswerIndex: 0,
              explanation: '99.99% uptime (four nines) allows approximately 52.6 minutes of total service downtime per calendar year.'
            }
          ]
        }
      }
    ]
  },
  {
    id: 'mod-tb-503',
    areaId: 'tb-503',
    title: 'Data-Driven Growth Marketing & Modern AdTech',
    description: 'Map out event clickstreams, MTA models, automation systems, and reverse ETL ingestion tracks.',
    libraryLinks: [
      { title: "Digital Marketing Analytics Foundations", url: "https://www.youtube.com/watch?v=n7z_95Z45C4" },
      { title: "Reverse ETL Pipeline Lifecycle", url: "https://www.youtube.com/watch?v=vmsn7B8Wj-U" }
    ],
    lessons: [
      {
        id: 'tb503-l1',
        moduleId: 'mod-tb-503',
        title: 'Unit 1: Tracking Implementations & Attribution Pipelines',
        duration: 35,
        youtubeVideoId: 'n7z_95Z45C4',
        content: `### Marketing Attribution & Frontend Event Telemetry

Modern marketing relies on tracking consumer software actions precisely across web interfaces. This unit covers clickstream architecture and conversion attribution.

---

#### 1. Clickstream Data Architecture
* **Frontend Telemetry Scripts:** Injecting optimized JavaScript listeners (React) or SDK methods (iOS/Android) to monitor user scroll tracking, clicks, and page loads.
* **Managing Event Overhead:** Ensuring that heavy tracking scripts do not block the browser's thread, causing lag on the layout.

#### 2. Attribution Models
When a user clicks on four different online advertisements before finally buying a product, marketing teams must calculate how much credit goes to each touchpoint:
* **First-Touch:** Giving 100% of the value credit to the first source discovery.
* **Last-Touch:** Allocating credit entirely to the final conversion click.
* **Multi-Touch Attribution (MTA):** Writing complex, weighted algorithms to evaluate the performance of every digital touchpoint in the customer journey.`,
        quiz: {
          id: 'q-tb503-l1',
          title: 'Tracking & Attribution Check',
          questions: [
            {
              id: 'q-tb503-l1-1',
              text: 'In digital attribution, how does a "Multi-Touch" (MTA) paradigm compare to a "Last-Touch" paradigm?',
              options: ['It only evaluates the very first advertisement click', 'It distributes conversion credit across multiple marketing channels based on statistical weighting models', 'It records user voice logs in real-time', 'It disables cache memory storage'],
              correctAnswerIndex: 1,
              explanation: 'MTA models distribute conversion credit proportionally across different interactions, rather than putting 100% of the value on the final step.'
            }
          ]
        }
      },
      {
        id: 'tb503-l2',
        moduleId: 'mod-tb-503',
        title: 'Unit 2: Marketing Automations & Reverse ETL Architectures',
        duration: 30,
        youtubeVideoId: 'vmsn7B8Wj-U',
        content: `### Automation Engines & Reverse ETL

Modern analytics infrastructures utilize warehouses to consolidate data. Reverse ETL completes the loop by pushing database insights backward into active SaaS marketing systems.

---

#### 1. What is Reverse ETL?
* **Standard ETL:** Pulling logs from operational directories and consolidating them in centralized analytic warehouses (like Snowflake or BigQuery).
* **Reverse ETL:** Reading structured records internally inside the cloud warehouse and writing computed insights backward into active customer action systems (HubSpot, Salesforce, Facebook Pixel, Google Ads).

#### 2. Engineering Marketing Loops
Implementing automated data pipelines (Apache Airflow or dbt) allows technical marketing networks to trigger hyper-personalized campaign flows:
* **Calculated Metrics Sync:** Automatically pushing calculated user propensity indices from warehouse datasets into corporate CRM interfaces.
* **Automated Audience Segments:** Syncing target churn alerts directly to Google and Facebook ad platforms to serve retention ads on external networks automatically.`,
        quiz: {
          id: 'q-tb503-l2',
          title: 'AdTech Automation Check',
          questions: [
            {
              id: 'q-tb503-l2-1',
              text: 'Which architectural direction describes a standard Reverse ETL pipeline operational layout?',
              options: ['From client browsers to transactional databases', 'From centralized analytical warehouses to operational SaaS business tools and CRMs', 'From uncompressed CSV files to system log directories', 'From external API scrapers into AWS S3 buckets'],
              correctAnswerIndex: 1,
              explanation: 'Reverse ETL is the process of moving pre-calculated analytical records from a data warehouse (like BigQuery or Snowflake) back into operational tools (like HubSpot, Salesforce, etc.).'
            }
          ]
        }
      }
    ]
  },
  {
    id: 'mod-tb-504',
    areaId: 'tb-504',
    title: 'Developer-Led Growth (B2B Marketing for Dev Tools)',
    description: 'Transform Developer Experience (DX) into a marketing vector and leverage open-source communities.',
    libraryLinks: [
      { title: "The Value of Great DX - Techworld with Nana", url: "https://www.youtube.com/watch?v=fXWfN_G7O3Y" },
      { title: "What is Developer Relations & Marketing?", url: "https://www.youtube.com/watch?v=2rreR5Fv_Yc" }
    ],
    lessons: [
      {
        id: 'tb504-l1',
        moduleId: 'mod-tb-504',
        title: 'Unit 1: Developer Experience (DX) as a Marketing Vector',
        duration: 30,
        youtubeVideoId: 'fXWfN_G7O3Y',
        content: `### Developer Experience (DX) as a Marketing Vector

When marketing to engineers, traditional outbound ad campaigns collapse. High retention and growth are driven primarily by a polished Developer Experience (DX).

---

#### 1. Developer-Led Growth (DLG)
* **Underlying Philosophy:** Software developers are highly resistant to standard high-pitch brand commercials. Instead, they prefer frictionless self-adoption.
* **The "Time-to-Hello-World" Constraint:** The duration it takes for an engineer to read a product page, install the package, call the API, and receive a success code inside their local terminal. Excellent DX targets a time under 5 minutes.

#### 2. Scaling Developer-First Offerings
To market a dev tool successfully, your engineering design *is* the marketing:
* **Worthy Technical Documentation:** Generating Swagger / OpenAPI interactive playgrounds, offering copyable, working code snippets, and maintaining clean API structures.
* **Open-Source SDK kits:** Providing official wrappers in leading programming environments (JavaScript, Python, Go) to avoid tedious manual setup loops.`,
        quiz: {
          id: 'q-tb504-l1',
          title: 'DX Marketing Check',
          questions: [
            {
              id: 'q-tb504-l1-1',
              text: 'In Developer-Led Growth (DLG), what does the metric "Time-to-Hello-World" evaluate?',
              options: ['The total compile time of a production app build script', 'The user duration required to register a brand domain', 'The duration it takes for an engineer to install, run, and successfully execute a simple initial integration with a developer service', 'The frequency of promotional social media posts'],
              correctAnswerIndex: 2,
              explanation: 'Time-to-Hello-World measures how fast an engineer can successfully fetch a test payload from a tool, which serves as a major driver for dev-tool growth.'
            }
          ]
        }
      },
      {
        id: 'tb504-l2',
        moduleId: 'mod-tb-504',
        title: 'Unit 2: SEO for Complex Terms & Open-Source Footprints',
        duration: 30,
        youtubeVideoId: '2rreR5Fv_Yc',
        content: `### SEO & Open-Source Community Engineering

Building a developer brand requires active community engagement, technical authority, and organic discoverability. This unit covers DevRel and specialized technical SEO.

---

#### 1. Specialized Technical SEO for Engineers
Traditional SEO practices target broad keywords. Technical SEO targets specific, low-volume, high-intent engineering queries:
* **Solving Niche Problems:** Creating deep architectural write-ups (e.g., *"How to configure Nginx proxies to bypass CORS errors on local web containers"*), bringing highly qualified engineers directly to your brand.
* **Educational Dev Blogs:** Prioritizing concrete code files and structural network diagrams over repetitive marketing copy.

#### 2. Open-Source Ecosystems & DevRel
* **Developer Relations (DevRel):** Operating as active connectors between the internal product and external communities.
* **Managing Github Footprints:** Providing robust starter templates, maintaining open issue trackers, and welcoming community contributions. Building an active, helpful open-source community around a tool is the ultimate way to drive organic, word-of-mouth adoption.`,
        quiz: {
          id: 'q-tb504-l2',
          title: 'DevRel & Community Check',
          questions: [
            {
              id: 'q-tb504-l2-1',
              text: 'What is the primary objective of a Developer Relations (DevRel) functional organization?',
              options: ['To cold-call corporate marketing executives', 'To build genuine bidirectional relationships with the developer community, fostering organic product trust and engagement', 'To enforce strict visual brand rules on social websites', 'To run automated end-to-end integration test runs'],
              correctAnswerIndex: 1,
              explanation: 'DevRel teams focus on building authentic, peer-to-peer relationships with developers by helping them solve real technical problems, which organically drives adoption.'
            }
          ]
        }
      }
    ]
  }
];
